name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 # Use the latest stable Node.js version

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Netlify with Yarn
        run: yarn global add netlify-cli@17.10.1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
